example_TNS.py
julianbautista/baopy pull request #5
Opened 2022-12-01 20:43 UTC by vincenzoaronica

example_TNS.pyyyyeaaahhhhh

2022-12-01 21:55 UTC, julianbautista commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +        data_file='data.ecsv',
Il faudrait utiliser les fichiers qui existent dans examples/DR16_eBOSS_LRG
D'ailleurs, tu as fait une branch d'une vielle version de baopy. 
Je crois qu'il y a pas de conflit maintenant, mais essaie de mettre à jour avant de faire la branch.

2022-12-01 21:55 UTC, julianbautista commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +dat.inverse_cova(nmocks=nmocks)
nmocks not defined?

2022-12-01 21:56 UTC, julianbautista commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +mod = baopy.models.RSD_TNS(
Il faudra rajouter ces fichiers dans example/DR16_eBOSS_LRG (ou un nouvel dossier) ainsi que le Pk_lin et une indication pour pyregpt

2022-12-01 21:58 UTC, julianbautista commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +tab = Table({
il faudrait que les noms des parametres soient consistants avec les noms plus haut

2022-12-01 22:01 UTC, julianbautista requested changes
bien! voici quelques petits commentaires

2022-12-01 22:01 UTC, julianbautista commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +tab.write('chain_mcmc.ecsv',overwrite=True)
cette sauvegarde peut être inclue aussi comme une fonction dans la class Sampler 
on ferait du coup 
`mcmc.save('chain_mcmc.ecsv')`

2022-12-02 10:00 UTC, vincenzoaronica commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +mod = baopy.models.RSD_TNS(
yes

2022-12-02 10:00 UTC, vincenzoaronica commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +tab = Table({
yes

2022-12-02 10:00 UTC, vincenzoaronica commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +tab.write('chain_mcmc.ecsv',overwrite=True)
c'est mieux

2022-12-02 14:23 UTC, vincenzoaronica commented on examples/DR16_LRG_postrecon/fit_TNS_model.py
> +tab.write('chain_mcmc.ecsv',overwrite=True)
c'est fait

2022-12-02 15:15 UTC, closed without merging